InfoManagingSystem/urls.py
from django.conf.urls import url

from app.views import *

urlpatterns = [
    url(r'^$', homepage, name='homepage'),
    url(r'^login/', loginpage, name='loginpage'),
    url(r'^password/', passwordpage, name='password'),
    url(r'^logout/', logout, name='logout'),
    url(r'^tutor/', tutorpage, name='tutorpage'),
    url(r'^edit-tutor/(\S+)/', edit_tutor, name='edit_tutor'),
    url(r'^delete-tutor/(\S+)/', delete_tutor, name='delete_tutor'),
    url(r'^teacher/', teacherpage, name='teacherpage'),
    url(r'^edit-teacher/(\S+)/', edit_teacher, name='edit_teacher'),
    url(r'^delete-teacher/(\S+)/', delete_teacher, name='delete_teacher'),
    url(r'^course/', coursepage, name='coursepage'),
    url(r'^edit-course/(\S+)/', edit_course, name='edit_course'),
    url(r'^course-teacher/(\S+)/', course_teacher, name='course_teacher'),
    url(r'^delete-course-teacher/(\S+)/(\S+)/', delete_course_teacher, name='delete_course_teacher'),
    url(r'^delete-course/(\S+)/', delete_course, name='delete_course'),
    url(r'^student/', studentpage, name='studentpage'),
    url(r'^edit-student/(\S+)/', edit_student, name='edit_student'),
    url(r'^delete-student/(\S+)/', delete_student, name='delete_student'),
    url(r'^delete-select/(\S+)/(\S+)/', delete_select, name='delete_select'),
    url(r'^add-time/(\S+)/(\S+)/', add_time, name='add_time'),
    url(r'^sub-time/(\S+)/(\S+)/', sub_time, name='sub_time'),
    url(r'^class/(\S+)/', classpage, name='classpage'),
    url(r'^edit-class/(\S+)/', edit_class, name='edit-class'),
    url(r'^delete-class/(\S+)/', delete_class, name='delete-class'),
    url(r'^add-teacher-time/(\S+)/', add_teacher_time, name='add_teacher_time'),
    url(r'^sub-teacher-time/(\S+)/', sub_teacher_time, name='sub_teacher_time'),
    url(r'^teacher-record/(\S+)/', teacherrecordpage, name='teacherrecordpage'),
    url(r'^edit-teacher-record/(\S+)/', edit_teacher_record, name='edit_teacher_record'),
    url(r'^delete-teacher-record/(\S+)/', delete_teacher_record, name='delete_teacher_record'),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User


class Student(models.Model):
    # 学生
    TYPE_CHOICES = (
        (1, '一对一教学'),
        (2, '自习'),
        (3, '一对一 + 自习'),
    )
    name = models.CharField(max_length=32)
    type = models.IntegerField(choices=TYPE_CHOICES)

    tutor = models.ForeignKey(to='Tutor', related_name='student')               # 所属班主任


class Teacher(models.Model):
    # 教师
    name = models.CharField(max_length=32)
    phone = models.CharField(max_length=32)
    time = models.IntegerField(default=0)

    course = models.ManyToManyField(to='Course', related_name='teacher')             # 教授科目


class Tutor(models.Model):
    # 班主任
    name = models.CharField(max_length=32)
    phone = models.CharField(max_length=32)

    user = models.OneToOneField(to=User, related_name='tutor')  # 绑定的账号


class Admin(models.Model):
    # 管理员
    name = models.CharField(max_length=32)
    phone = models.CharField(max_length=32)

    user = models.OneToOneField(to=User, related_name='admin')  # 绑定的账号


class Course(models.Model):
    # 科目
    name = models.CharField(max_length=128)
    index = models.CharField(max_length=16, unique=True)
    teacher_num = models.IntegerField(default=0)


class CourseSelect(models.Model):
    # 学生所选科目
    course = models.ForeignKey(Course, related_name='select')           # 所选科目
    student = models.ForeignKey(Student, related_name='select')         # 学生
    teacher = models.ForeignKey(Teacher, related_name='select')         # 老师
    time = models.IntegerField(default=0)                               # 剩余课时


class CommentType(models.Model):
    # 评价类型
    name = models.CharField(max_length=64, unique=True)


class Comment(models.Model):
    # 评价
    type = models.ForeignKey(to='CommentType', related_name='comment')
    content = models.TextField()
    score = models.IntegerField()


class ClassRecord(models.Model):
    # 上课记录
    SCHOOL_CHOICES = (
        (1, '小学'),
        (2, '初中'),
        (3, '高中'),
    )
    GRADE_CHOICES = (
        (1, '一年级'),
        (2, '二年级'),
        (3, '三年级'),
        (4, '四年级'),
        (5, '五年级'),
    )
    COURSE_CHOICES = (
        (1, '语文'),
        (2, '数学'),
        (3, '外语'),
        (4, '物理'),
        (5, '化学'),
        (6, '生物'),
    )
    BOOK_CHOICES = (
        (1, '上册'),
        (2, '下册'),
    )
    UNIT_CHOICES = (
        (1, '第一单元'),
        (2, '第二单元'),
        (3, '第三单元'),
        (4, '第四单元'),
        (5, '第五单元'),
        (6, '第六单元'),
        (7, '第七单元'),
        (8, '第八单元'),
        (9, '第九单元'),
    )

    STUDY_CHOICES = (
        (1, '学习状态：学习状态不佳，注意力无法集中'),
        (2, '学习状态：刚开始上课注意力较为集中，但无法维持良好的学习状态，注意力分散较快'),
        (3, '学习状态：刚开始上课注意力不集中，但稍后就有改善。'),
        (4, '学习状态：注意力较为集中，学习状态不错'),
    )
    KNOWLEDGE_CHOICES = (
        (1, '知识接受情况：知识接受情况较差，听不进去课'),
        (2, '知识接受情况：知识接受情况较差，可以接受，但不能理解'),
        (3, '知识接受情况：知识接受情况良好，讲到的内容都可以接受')
    )
    PRACTICE_CHOICES = (
        (1, '练习反馈：练习表现较差，知识未能消化，还需要对知识点进行巩固复习和多加练习'),
        (2, '练习反馈：练习状况良好，但并未能完全掌握所学的内容，需要多加练习'),
        (3, '练习反馈：练习完成情况不错，能熟练的运用学到的知识'),
    )

    student = models.ForeignKey(to=Student, related_name='record')
    school = models.IntegerField(choices=SCHOOL_CHOICES)
    grade = models.IntegerField(choices=GRADE_CHOICES)
    course = models.IntegerField(choices=COURSE_CHOICES)
    book = models.IntegerField(choices=BOOK_CHOICES)
    unit = models.IntegerField(choices=UNIT_CHOICES)
    note = models.TextField(null=True)

    study = models.IntegerField(choices=STUDY_CHOICES)
    knowledge = models.IntegerField(choices=KNOWLEDGE_CHOICES)
    practice = models.IntegerField(choices=PRACTICE_CHOICES)
    study_note = models.TextField(null=True)

    date = models.DateField()


class TeacherRecord(models.Model):
    # 上课记录
    SCHOOL_CHOICES = (
        (1, '小学'),
        (2, '初中'),
        (3, '高中'),
    )
    GRADE_CHOICES = (
        (1, '一年级'),
        (2, '二年级'),
        (3, '三年级'),
        (4, '四年级'),
        (5, '五年级'),
    )
    COURSE_CHOICES = (
        (1, '语文'),
        (2, '数学'),
        (3, '外语'),
        (4, '物理'),
        (5, '化学'),
        (6, '生物'),
    )
    BOOK_CHOICES = (
        (1, '上册'),
        (2, '下册'),
    )
    UNIT_CHOICES = (
        (1, '第一单元'),
        (2, '第二单元'),
        (3, '第三单元'),
        (4, '第四单元'),
        (5, '第五单元'),
        (6, '第六单元'),
        (7, '第七单元'),
        (8, '第八单元'),
        (9, '第九单元'),
    )

    STUDY_CHOICES = (
        (1, '学习状态：学习状态不佳，注意力无法集中'),
        (2, '学习状态：刚开始上课注意力较为集中，但无法维持良好的学习状态，注意力分散较快'),
        (3, '学习状态：刚开始上课注意力不集中，但稍后就有改善。'),
        (4, '学习状态：注意力较为集中，学习状态不错'),
    )
    KNOWLEDGE_CHOICES = (
        (1, '知识接受情况：知识接受情况较差，听不进去课'),
        (2, '知识接受情况：知识接受情况较差，可以接受，但不能理解'),
        (3, '知识接受情况：知识接受情况良好，讲到的内容都可以接受')
    )
    PRACTICE_CHOICES = (
        (1, '练习反馈：练习表现较差，知识未能消化，还需要对知识点进行巩固复习和多加练习'),
        (2, '练习反馈：练习状况良好，但并未能完全掌握所学的内容，需要多加练习'),
        (3, '练习反馈：练习完成情况不错，能熟练的运用学到的知识'),
    )

    teacher = models.ForeignKey(to=Teacher, related_name='record')
    school = models.IntegerField(choices=SCHOOL_CHOICES)
    grade = models.IntegerField(choices=GRADE_CHOICES)
    course = models.IntegerField(choices=COURSE_CHOICES)
    book = models.IntegerField(choices=BOOK_CHOICES)
    unit = models.IntegerField(choices=UNIT_CHOICES)
    note = models.TextField(null=True)

    study = models.IntegerField(choices=STUDY_CHOICES)
    knowledge = models.IntegerField(choices=KNOWLEDGE_CHOICES)
    practice = models.IntegerField(choices=PRACTICE_CHOICES)
    study_note = models.TextField(null=True)

    date = models.DateField()

app/templates/classpage.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}学生上课信息{% endblock %}

{% block cur %}学生上课信息 - {{ student.name }}{% endblock %}

{% block content %}
  <div class="admin-content">
    <div class="admin-content-body">
      <hr>

      <div class="am-g">
        <div class="am-u-sm-12 am-u-md-6">
          <div class="am-btn-toolbar">
            <div class="am-btn-group am-btn-group-xs">
              <button type="button" class="am-btn am-btn-default" data-am-modal="{target: '#new-student', closeViaDimmer: 0, width: 800}"><span class="am-icon-plus"></span> 新增</button>
              {% if post and error %}
                <button type="button" class="am-btn am-btn-danger" disabled="disabled">{{ reason }}</button>
              {% endif %}
            </div>
          </div>
        </div>
        <!--<div class="am-u-sm-12 am-u-md-6">-->
          <!--<form method="get">-->
            <!--<div class="am-input-group am-input-group-sm">-->
              <!--<input type="text" class="am-form-field" name="search" value="{{ search }}">-->
              <!--<span class="am-input-group-btn">-->
                <!--<button class="am-btn am-btn-default" type="submit">搜索</button>-->
              <!--</span>-->
            <!--</div>-->
          <!--</form>-->
        <!--</div>-->
      </div>

      <div class="am-g">
        <div class="am-u-sm-12">
          <form class="am-form">
            <table class="am-table am-table-striped am-table-hover table-main">
              <thead>
              <tr>
                <th>日期</th>
                <th>学习内容</th>
                <th>评价</th>
                {% if user.is_admin %}
                <th>操作</th>
                {% endif %}
              </tr>
              </thead>
              <tbody>
              {% for i in records %}
              <tr>
                <td><small>{{ i.date }}</small></td>
                <td><small>{{ i.get_school_display }}{{ i.get_grade_display }}<br/>{{ i.get_course_display }}{{ i.get_book_display }}{{ i.get_unit_display }}<br/>{{ i.note }}</small></td>
                <td><small>{{ i.get_study_display }}<br/>{{ i.get_knowledge_display }}<br/>{{ i.get_practice_display }}<br/>{{ i.get_sdudy_note_display }}</small></td>
                {% if user.is_admin %}
                <td>
                  <div class="am-btn-toolbar">
                    <div class="am-btn-group am-btn-group-xs">
                      <a class="am-btn am-btn-default am-btn-xs am-text-secondary" href="/edit-class/{{ i.id }}/"><span class="am-icon-pencil-square-o"></span>编辑</a><br/>
                      <a class="am-btn am-btn-default am-btn-xs am-text-danger" href="/delete-class/{{ i.id }}/"><span class="am-icon-trash-o"></span>删除</a>
                    </div>
                  </div>
                </td>
                {% endif %}
              </tr>
              {% endfor %}
              </tbody>
            </table>
            <hr />
          </form>
        </div>

      </div>
    </div>

  </div>

  <div class="am-modal am-modal-no-btn" tabindex="-1" id="new-student">
    <div class="am-modal-dialog">
      <div class="am-modal-hd">添加 上课 信息
        <a href="javascript: void(0)" class="am-close am-close-spin" data-am-modal-close>&times;</a>
      </div>
      <div class="am-modal-bd">
        <form method="post" class="am-form">
          {% csrf_token %}
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">日期</span>
            <input type="date" class="am-form-field" name="date" data-am-datepicker readonly required/>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">学校</span>
            <select class="am-form-field" name="school">
            {% for i in school_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">年级</span>
            <select class="am-form-field" name="grade">
            {% for i in grade_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">课程</span>
            <select class="am-form-field" name="course">
            {% for i in course_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">书</span>
            <select class="am-form-field" name="book">
            {% for i in book_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">单元</span>
            <select class="am-form-field" name="unit">
            {% for i in unit_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">备注</span>
            <input type="text" maxlength="16" class="am-form-field" name="note" placeholder="note">
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">学习情况</span>
            <select class="am-form-field" name="study">
            {% for i in study_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">知识接受情况</span>
            <select class="am-form-field" name="knowledge">
            {% for i in knowledge_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">练习反馈</span>
            <select class="am-form-field" name="practice">
            {% for i in practice_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">备注</span>
            <input type="text" maxlength="16" class="am-form-field" name="study_note" placeholder="study_note">
          </div>
          <br/>
          <br/>
          <div class="am-cf am-u-xs-12">
            <input type="submit" name="" value="创 建" class="am-btn am-btn-primary am-btn-sm am-fl am-u-xs-12">
          </div>
          <br/>
          <br/>
        </form>
      </div>
    </div>
  </div>

  <!-- content end -->

{% endblock %}

app/templates/homepage.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}首页{% endblock %}

{% block cur %}首页{% endblock %}

app/templates/studentpage.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}学生管理{% endblock %}

{% block cur %}学生管理{% endblock %}

{% block content %}

  <div class="admin-content">
    <div class="admin-content-body">
      <hr>

      <div class="am-g">
        <div class="am-u-sm-12 am-u-md-6">
          <div class="am-btn-toolbar">
            <div class="am-btn-group am-btn-group-xs">
              <button type="button" class="am-btn am-btn-default" data-am-modal="{target: '#new-student', closeViaDimmer: 0}"><span class="am-icon-plus"></span> 新增</button>
              {% if post and error %}
                <button type="button" class="am-btn am-btn-danger" disabled="disabled">{{ reason }}</button>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="am-u-sm-12 am-u-md-6">
          <form method="get">
            <div class="am-input-group am-input-group-sm">
              <input type="text" class="am-form-field" name="search" value="{{ search }}">
              <span class="am-input-group-btn">
                <button class="am-btn am-btn-default" type="submit">搜索</button>
              </span>
            </div>
          </form>
        </div>
      </div>

      <div class="am-g">
        <div class="am-u-sm-12">
          <form class="am-form">
            <table class="am-table am-table-striped am-table-hover table-main">
              <thead>
              <tr>
                <th>编号</th>
                <th>姓名</th>
                <th>类型</th>
                <th>班主任</th>
                <th>操作</th>
              </tr>
              </thead>
              <tbody>
              {% for i in students %}
              <tr>
                <td>{{ i.id }}</td>
                <td><a href="/edit-student/{{ i.id }}/">{{ i.name }}</a></td>
                <td>{{ i.get_type_display }}</td>
                <td>{{ i.tutor.name }}</td>
                <td>
                  <div class="am-btn-toolbar">
                    <div class="am-btn-group am-btn-group-xs">
                      {% if user.is_admin %}
                      <a class="am-btn am-btn-default am-btn-xs am-text-secondary" href="/edit-student/{{ i.id }}/"><span class="am-icon-pencil-square-o"></span>管理</a>
                      {% endif %}
                      <a class="am-btn am-btn-default am-btn-xs am-text-secondary" href="/class/{{ i.id }}/"><span class="am-icon-pencil-square-o"></span>上课</a>
                      {% if user.is_admin %}<a class="am-btn am-btn-default am-btn-xs am-text-danger" href="/delete-student/{{ i.id }}/"><span class="am-icon-trash-o"></span>删除</a>{% endif %}
                    </div>
                  </div>
                </td>
              </tr>
              {% endfor %}
              </tbody>
            </table>
            <hr />
          </form>
        </div>

      </div>
    </div>

  </div>

  <div class="am-modal am-modal-no-btn" tabindex="-1" id="new-student">
    <div class="am-modal-dialog">
      <div class="am-modal-hd">添加 学生 信息
        <a href="javascript: void(0)" class="am-close am-close-spin" data-am-modal-close>&times;</a>
      </div>
      <div class="am-modal-bd">
        <form method="post" class="am-form">
          {% csrf_token %}
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">姓名</span>
            <input type="text" maxlength="16" class="am-form-field" name="name" placeholder="name">
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">类型</span>
            <select class="am-form-field" name="type">
              {% for i in choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
              {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">班主任</span>
            <select class="am-form-field" name="tutor">
              {% for i in tutors %}
              <option value="{{ i.id }}">{{ i.id }} - {{ i.name }}</option>
              {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-cf am-u-xs-12">
            <input type="submit" name="" value="创 建" class="am-btn am-btn-primary am-btn-sm am-fl am-u-xs-12">
          </div>
          <br/>
          <br/>
        </form>
      </div>
    </div>
  </div>

  <!-- content end -->

{% endblock %}

app/templates/teacherrecordpage.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}教师上课信息{% endblock %}

{% block cur %}教师上课信息 - {{ teacher.name }}{% endblock %}

{% block content %}
  <div class="admin-content">
    <div class="admin-content-body">
      <hr>

      <div class="am-g">
        <div class="am-u-sm-12 am-u-md-6">
          <div class="am-btn-toolbar">
            <div class="am-btn-group am-btn-group-xs">
              <button type="button" class="am-btn am-btn-default" data-am-modal="{target: '#new-record', closeViaDimmer: 0, width: 800}"><span class="am-icon-plus"></span> 新增</button>
              {% if post and error %}
                <button type="button" class="am-btn am-btn-danger" disabled="disabled">{{ reason }}</button>
              {% endif %}
            </div>
          </div>
        </div>
        <!--<div class="am-u-sm-12 am-u-md-6">-->
          <!--<form method="get">-->
            <!--<div class="am-input-group am-input-group-sm">-->
              <!--<input type="text" class="am-form-field" name="search" value="{{ search }}">-->
              <!--<span class="am-input-group-btn">-->
                <!--<button class="am-btn am-btn-default" type="submit">搜索</button>-->
              <!--</span>-->
            <!--</div>-->
          <!--</form>-->
        <!--</div>-->
      </div>

      <div class="am-g">
        <div class="am-u-sm-12">
          <form class="am-form">
            <table class="am-table am-table-striped am-table-hover table-main">
              <thead>
              <tr>
                <th>日期</th>
                <th>学习内容</th>
                <th>评价</th>
                {% if user.is_admin %}
                <th>操作</th>
                {% endif %}
              </tr>
              </thead>
              <tbody>
              {% for i in records %}
              <tr>
                <td><small>{{ i.date }}</small></td>
                <td><small>{{ i.get_school_display }}{{ i.get_grade_display }}<br/>{{ i.get_course_display }}{{ i.get_book_display }}{{ i.get_unit_display }}<br/>{{ i.note }}</small></td>
                <td><small>{{ i.get_study_display }}<br/>{{ i.get_knowledge_display }}<br/>{{ i.get_practice_display }}<br/>{{ i.get_sdudy_note_display }}</small></td>
                {% if user.is_admin %}
                <td>
                  <div class="am-btn-toolbar">
                    <div class="am-btn-group am-btn-group-xs">
                      <a class="am-btn am-btn-default am-btn-xs am-text-secondary" href="/edit-teacher-record/{{ i.id }}/"><span class="am-icon-pencil-square-o"></span>编辑</a><br/>
                      <a class="am-btn am-btn-default am-btn-xs am-text-danger" href="/delete-teacher-record/{{ i.id }}/"><span class="am-icon-trash-o"></span>删除</a>
                    </div>
                  </div>
                </td>
                {% endif %}
              </tr>
              {% endfor %}
              </tbody>
            </table>
            <hr />
          </form>
        </div>

      </div>
    </div>

  </div>

  <div class="am-modal am-modal-no-btn" tabindex="-1" id="new-record">
    <div class="am-modal-dialog">
      <div class="am-modal-hd">添加 上课 信息
        <a href="javascript: void(0)" class="am-close am-close-spin" data-am-modal-close>&times;</a>
      </div>
      <div class="am-modal-bd">
        <form method="post" class="am-form">
          {% csrf_token %}
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">日期</span>
            <input type="date" class="am-form-field" name="date" data-am-datepicker readonly required/>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">学校</span>
            <select class="am-form-field" name="school">
            {% for i in school_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">年级</span>
            <select class="am-form-field" name="grade">
            {% for i in grade_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">课程</span>
            <select class="am-form-field" name="course">
            {% for i in course_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">书</span>
            <select class="am-form-field" name="book">
            {% for i in book_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">单元</span>
            <select class="am-form-field" name="unit">
            {% for i in unit_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">备注</span>
            <input type="text" maxlength="16" class="am-form-field" name="note" placeholder="note">
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">学习情况</span>
            <select class="am-form-field" name="study">
            {% for i in study_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">知识接受情况</span>
            <select class="am-form-field" name="knowledge">
            {% for i in knowledge_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">练习反馈</span>
            <select class="am-form-field" name="practice">
            {% for i in practice_choices %}
              <option value="{{ i.0 }}">{{ i.1 }}</option>
            {% endfor %}
            </select>
          </div>
          <br/>
          <br/>
          <div class="am-input-group am-u-xs-12">
            <span class="am-input-group-label">备注</span>
            <input type="text" maxlength="16" class="am-form-field" name="study_note" placeholder="study_note">
          </div>
          <br/>
          <br/>
          <div class="am-cf am-u-xs-12">
            <input type="submit" name="" value="创 建" class="am-btn am-btn-primary am-btn-sm am-fl am-u-xs-12">
          </div>
          <br/>
          <br/>
        </form>
      </div>
    </div>
  </div>

  <!-- content end -->

{% endblock %}